name: build-test-deploy
on: push
jobs: 
  setup-node-job:
    runs-on: ubuntu-latest
    steps: 
      - name: use node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22.x'
          
