name: hello-world
on: push
jobs: 
  hello-world-job:
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v5
      - run: echo "$(cat hello_world.txt)"

      - name: Ferris say Hello
        uses: vm-mscs-mmxxiv/hello-ferris@v0.0.2


      - name: use node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22.x'
          
